import { Button } from "std-widgets.slint";
import { Dapp } from "dapp.slint";
export component DappTile inherits TouchArea {
    horizontal-stretch: 100;
    vertical-stretch: 100;
    in-out property <Dapp> dapp;
    callback select-dapp(Dapp);
    callback request-send-tokens();

    clicked => {
        // debug("DappTile: ", root.dapp);
        root.select-dapp(self.dapp);
    }

    Image {
        source: dapp.logo;
        width: parent.width;
        height: parent.height;
    }
}
