import { Button } from "std-widgets.slint";
import { Chain } from "chain.slint";

export component ChainSelect {
    height: 200px;
    in-out property <int> active-tab: 0;
    in-out property <Chain> active-chain;

    callback select-chain(Chain) -> Chain;

    VerticalLayout {
        tab_bar := HorizontalLayout {
            spacing: 3px;
            Button {
                text: "ETH";
                clicked => {
                    root.active-chain.name = "Ethereum";
                    root.select-chain(root.active-chain);
                    root.active-tab = 0;
                }
            }
            Button {
                text: "OP";
                clicked => { 
                    root.active-chain.name = "Optimism";
                    root.select-chain(root.active-chain);
                    root.active-tab = 1;
                }
            }
            Button {
                text: "ARB";
                clicked => { 
                    root.active-chain.name = "Arbitrum";
                    root.select-chain(root.active-chain);
                    root.active-tab = 2;
                }
            }
        }
        Rectangle {
            clip: true;
            Rectangle {
                background: gray;
                x: root.active-tab == 0 ? 0 : root.active-tab < 0 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
                    Text {
                    text: root.active-chain.name;
                }
            }
            Rectangle {
                background: red;
                x: root.active-tab == 1 ? 0 : root.active-tab < 1 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
                Text {
                    text: root.active-chain.name;
                }
            }
            Rectangle {
                background: blue;
                x: root.active-tab == 2 ? 0 : root.active-tab < 2 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
                Text {
                    text: root.active-chain.name;
                }
            }
        }
    }
}