import { Button, VerticalBox, StandardListView, LineEdit } from "std-widgets.slint";
import { ChainSelect } from "chain_select.slint";
import { DappGrid } from "dapps/dapp_grid.slint";
import { SendSVG } from "send_svg.slint";
import { SendButton } from "send_button.slint";
import { Dapp } from "dapps/dapp.slint";
export struct Chain {
    name: string,
    chain_id: int,
}

global App {
    in-out property <Dapp> dapp;
    in-out property <Chain> chain: {name: "Ethereum", chain_id: 1};
}

export component AppWindow inherits Window {
    preferred-height: 800px;
    width: 400px;
    in-out property<Chain> active-chain: App.chain;
    in-out property<Dapp> active-dapp: App.dapp;
    in property <[int]> balances;

    callback request-open-dapp();
    callback request-all-balances <=> BALANCES_btn.clicked;
    callback request-send-tokens();
    callback request-dapp-config(Dapp);

    VerticalBox {
        ChainSelect {}

        DappGrid {}

        Text {
            text: "Active: " + root.active-chain.name; 
            height: 32px;
        }

        BALANCES_btn := Button {
            text: "Balances";
            height: 32px;
        }

        SendButton {
            request-send-tokens => {
                root.request-send-tokens();
            }
        }
    }    
}