import { Button, VerticalBox, StandardListView, LineEdit } from "std-widgets.slint";
import { ChainSelect } from "chain_select.slint";
import { DappTile } from "dapp_tile.slint";
import { Uniswap } from "dapps/uniswap.slint";

export struct Chain {
    name: string,
    chain_id: int,
}

global App {
    in-out property <Chain> chain: {name: "Ethereum", chain_id: 1};
}

export component AppWindow inherits Window {
    in-out property<string> dapp: "Uniswap";
    in-out property<Chain> chain: App.chain;
    in property <[int]> balances;
    property <bool> active: true;

    callback request-open-dapp();
    callback request-all-balances <=> BALANCES_btn.clicked;
    callback request-send-tokens <=> SEND_btn.clicked;

    VerticalBox {
        ChainSelect {
            // chain-updated => {
            //     // Update the global App.chain
            //     return chain; 
            // }
        }


        // DAPP
        // uniswapBtn := Button {
        //     text: "Uniswap";
        //     clicked => {
        //         root.request-open-dapp();
        //     }
        // }
        GridLayout {
            spacing: 6px;
            Row {
                Uniswap {}
                Uniswap {}
                Uniswap {}
            }
            Row {
                Uniswap {}
                Uniswap {}
                Uniswap {}
            }
            // DappTile {}
            // DappTile {}
        }

        Text {
            text: "Current chain: " + root.chain.name; 
        }

        BALANCES_btn := Button {
            text: "Balances";
        }

        SEND_btn := Button {
            text: "Send";
        }
    }    
}
