import { Button } from "std-widgets.slint";
// import { Chain } from "./appwindow.slint";

export component ChainSelect inherits Window {
    preferred-height: 200px;
    in-out property <int> active-tab: 0;
    in-out property <string> active-chain: "Ethereum";
    callback chain-updated(int, string);

    VerticalLayout {
        tab_bar := HorizontalLayout {
            spacing: 3px;
            Button {
                text: "ETH";
                clicked => { root.chain-updated(0, "Ethereum"); }
            }
            Button {
                text: "OP";
                clicked => { root.chain-updated(1, "Optimism"); }
            }
            Button {
                text: "ARB";
                clicked => { root.chain-updated(2, "Arbitrum");}
            }
        }
        Rectangle {
            clip: true;
            Rectangle {
                background: gray;
                x: root.active-tab == 0 ? 0 : root.active-tab < 0 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
                    Text {
                    text: root.active-chain;
                }
            }
            Rectangle {
                background: red;
                x: root.active-tab == 1 ? 0 : root.active-tab < 1 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
                Text {
                    text: root.active-chain;
                }
            }
            Rectangle {
                background: blue;
                x: root.active-tab == 2 ? 0 : root.active-tab < 2 ? - self.width - 1px : parent.width + 1px;
                animate x { duration: 125ms; easing: ease; }
                Text {
                    text: root.active-chain;
                }
            }
        }
    }
}